// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { ApplyJobsData, ApplyJobsResponses, ApproveJobData, ApproveJobResponses, AuthenticateUserData, AuthenticateUserResponses, ChangeAvatarData, ChangeAvatarResponses, ChangePasswordData, ChangePasswordResponses, CloseJobPostingData, CloseJobPostingResponses, CreateCompanyData, CreateCompanyResponses, CreateJobPostingData, CreateJobPostingResponses, DeleteJobData, DeleteJobPostingData, DeleteJobPostingResponses, DeleteJobResponses, DeleteResumeData, DeleteResumeResponses, GetCompanyData, GetCompanyProfileData, GetCompanyProfileResponses, GetCompanyResponses, GetJobApplicationDetailData, GetJobApplicationDetailResponses, GetJobApplicationsData, GetJobApplicationsResponses, GetJobDetail2Data, GetJobDetail2Responses, GetJobDetailData, GetJobDetailResponses, GetJobPreferenceData, GetJobPreferenceResponses, GetJobsData, GetJobsResponses, GetMyApplicationsData, GetMyApplicationsResponses, GetMyJobDetailData, GetMyJobDetailResponses, GetMyJobsData, GetMyJobsResponses, GetMyProfileData, GetMyProfileResponses, GetMyResumesData, GetMyResumesResponses, LogoutUserData, LogoutUserResponses, PutApplicationUnderReviewData, PutApplicationUnderReviewResponses, RegisterUserData, RegisterUserResponses, RejectJobData, RejectJobResponses, ReopenJobPostingData, ReopenJobPostingResponses, RequestPasswordResetData, RequestPasswordResetResponses, ResetPasswordData, ResetPasswordResponses, SearchJobsData, SearchJobsResponses, UpdateApplicationStatusData, UpdateApplicationStatusResponses, UpdateCompanyData, UpdateCompanyResponses, UpdateJobPostingData, UpdateJobPostingResponses, UpdateJobPreferenceData, UpdateJobPreferenceResponses, UpdatePersonalInformationData, UpdatePersonalInformationResponses, UploadResumeData, UploadResumeResponses, ValidateResetTokenData, ValidateResetTokenResponses, WithdrawApplicationData, WithdrawApplicationResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getJobs = <ThrowOnError extends boolean = false>(options?: Options<GetJobsData, ThrowOnError>) => (options?.client ?? client).get<GetJobsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/jobs',
    ...options
});

export const getJobDetail = <ThrowOnError extends boolean = false>(options: Options<GetJobDetailData, ThrowOnError>) => (options.client ?? client).get<GetJobDetailResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/jobs/{jobId}',
    ...options
});

export const approveJob = <ThrowOnError extends boolean = false>(options: Options<ApproveJobData, ThrowOnError>) => (options.client ?? client).patch<ApproveJobResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/jobs/{jobId}/approve',
    ...options
});

export const rejectJob = <ThrowOnError extends boolean = false>(options: Options<RejectJobData, ThrowOnError>) => (options.client ?? client).patch<RejectJobResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/jobs/{jobId}/reject',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteJob = <ThrowOnError extends boolean = false>(options: Options<DeleteJobData, ThrowOnError>) => (options.client ?? client).patch<DeleteJobResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/jobs/{jobId}/delete',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getMyResumes = <ThrowOnError extends boolean = false>(options?: Options<GetMyResumesData, ThrowOnError>) => (options?.client ?? client).get<GetMyResumesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/resumes',
    ...options
});

export const uploadResume = <ThrowOnError extends boolean = false>(options: Options<UploadResumeData, ThrowOnError>) => (options.client ?? client).post<UploadResumeResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/resumes',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const deleteResume = <ThrowOnError extends boolean = false>(options: Options<DeleteResumeData, ThrowOnError>) => (options.client ?? client).delete<DeleteResumeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/resumes/{resumeId}',
    ...options
});

export const getCompanyProfile = <ThrowOnError extends boolean = false>(options: Options<GetCompanyProfileData, ThrowOnError>) => (options.client ?? client).get<GetCompanyProfileResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/companies/{companyId}',
    ...options
});

export const getMyProfile = <ThrowOnError extends boolean = false>(options?: Options<GetMyProfileData, ThrowOnError>) => (options?.client ?? client).get<GetMyProfileResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/profile',
    ...options
});

export const updatePersonalInformation = <ThrowOnError extends boolean = false>(options: Options<UpdatePersonalInformationData, ThrowOnError>) => (options.client ?? client).patch<UpdatePersonalInformationResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getJobPreference = <ThrowOnError extends boolean = false>(options?: Options<GetJobPreferenceData, ThrowOnError>) => (options?.client ?? client).get<GetJobPreferenceResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/job-preference',
    ...options
});

export const updateJobPreference = <ThrowOnError extends boolean = false>(options: Options<UpdateJobPreferenceData, ThrowOnError>) => (options.client ?? client).patch<UpdateJobPreferenceResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/job-preference',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const changeAvatar = <ThrowOnError extends boolean = false>(options: Options<ChangeAvatarData, ThrowOnError>) => (options.client ?? client).patch<ChangeAvatarResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/avatar',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>) => (options.client ?? client).patch<ChangePasswordResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const searchJobs = <ThrowOnError extends boolean = false>(options?: Options<SearchJobsData, ThrowOnError>) => (options?.client ?? client).get<SearchJobsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/jobs',
    ...options
});

export const getJobDetail2 = <ThrowOnError extends boolean = false>(options: Options<GetJobDetail2Data, ThrowOnError>) => (options.client ?? client).get<GetJobDetail2Responses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/jobs/{jobId}',
    ...options
});

export const applyJobs = <ThrowOnError extends boolean = false>(options: Options<ApplyJobsData, ThrowOnError>) => (options.client ?? client).post<ApplyJobsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/applications',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getMyApplications = <ThrowOnError extends boolean = false>(options?: Options<GetMyApplicationsData, ThrowOnError>) => (options?.client ?? client).get<GetMyApplicationsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/applications/my',
    ...options
});

export const withdrawApplication = <ThrowOnError extends boolean = false>(options: Options<WithdrawApplicationData, ThrowOnError>) => (options.client ?? client).patch<WithdrawApplicationResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/applications/{applicationId}/withdraw',
    ...options
});

export const getMyJobs = <ThrowOnError extends boolean = false>(options?: Options<GetMyJobsData, ThrowOnError>) => (options?.client ?? client).get<GetMyJobsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/jobs',
    ...options
});

export const createJobPosting = <ThrowOnError extends boolean = false>(options: Options<CreateJobPostingData, ThrowOnError>) => (options.client ?? client).post<CreateJobPostingResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/jobs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getMyJobDetail = <ThrowOnError extends boolean = false>(options: Options<GetMyJobDetailData, ThrowOnError>) => (options.client ?? client).get<GetMyJobDetailResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/jobs/{jobId}',
    ...options
});

export const updateJobPosting = <ThrowOnError extends boolean = false>(options: Options<UpdateJobPostingData, ThrowOnError>) => (options.client ?? client).patch<UpdateJobPostingResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/jobs/{jobId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const closeJobPosting = <ThrowOnError extends boolean = false>(options: Options<CloseJobPostingData, ThrowOnError>) => (options.client ?? client).patch<CloseJobPostingResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/jobs/{jobId}/close',
    ...options
});

export const reopenJobPosting = <ThrowOnError extends boolean = false>(options: Options<ReopenJobPostingData, ThrowOnError>) => (options.client ?? client).patch<ReopenJobPostingResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/jobs/{jobId}/reopen',
    ...options
});

export const deleteJobPosting = <ThrowOnError extends boolean = false>(options: Options<DeleteJobPostingData, ThrowOnError>) => (options.client ?? client).patch<DeleteJobPostingResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/jobs/{jobId}/delete',
    ...options
});

export const getCompany = <ThrowOnError extends boolean = false>(options?: Options<GetCompanyData, ThrowOnError>) => (options?.client ?? client).get<GetCompanyResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/company',
    ...options
});

export const updateCompany = <ThrowOnError extends boolean = false>(options: Options<UpdateCompanyData, ThrowOnError>) => (options.client ?? client).patch<UpdateCompanyResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/company',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const createCompany = <ThrowOnError extends boolean = false>(options: Options<CreateCompanyData, ThrowOnError>) => (options.client ?? client).post<CreateCompanyResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/company',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getJobApplications = <ThrowOnError extends boolean = false>(options: Options<GetJobApplicationsData, ThrowOnError>) => (options.client ?? client).get<GetJobApplicationsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/jobs/{jobId}/applications',
    ...options
});

export const getJobApplicationDetail = <ThrowOnError extends boolean = false>(options: Options<GetJobApplicationDetailData, ThrowOnError>) => (options.client ?? client).get<GetJobApplicationDetailResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/applications/{applicationId}',
    ...options
});

export const putApplicationUnderReview = <ThrowOnError extends boolean = false>(options: Options<PutApplicationUnderReviewData, ThrowOnError>) => (options.client ?? client).patch<PutApplicationUnderReviewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/applications/{applicationId}/under-review',
    ...options
});

export const updateApplicationStatus = <ThrowOnError extends boolean = false>(options: Options<UpdateApplicationStatusData, ThrowOnError>) => (options.client ?? client).patch<UpdateApplicationStatusResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/employer/applications/{applicationId}/status',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authenticateUser = <ThrowOnError extends boolean = false>(options: Options<AuthenticateUserData, ThrowOnError>) => (options.client ?? client).post<AuthenticateUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const registerUser = <ThrowOnError extends boolean = false>(options: Options<RegisterUserData, ThrowOnError>) => (options.client ?? client).post<RegisterUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logoutUser = <ThrowOnError extends boolean = false>(options?: Options<LogoutUserData, ThrowOnError>) => (options?.client ?? client).post<LogoutUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

export const requestPasswordReset = <ThrowOnError extends boolean = false>(options: Options<RequestPasswordResetData, ThrowOnError>) => (options.client ?? client).post<RequestPasswordResetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/forgot-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const resetPassword = <ThrowOnError extends boolean = false>(options: Options<ResetPasswordData, ThrowOnError>) => (options.client ?? client).post<ResetPasswordResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const validateResetToken = <ThrowOnError extends boolean = false>(options: Options<ValidateResetTokenData, ThrowOnError>) => (options.client ?? client).get<ValidateResetTokenResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/auth/reset-password/validate',
    ...options
});
