// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3000' | (string & {});
};

export type UserStatus = 'ACTIVE' | 'BANNED';

export type UserListItemDto = {
    userId: string;
    email: string;
    fullName: string | null;
    roleId: number;
    status: UserStatus;
    createdAt: string;
};

export type UserListResponse = {
    items: Array<UserListItemDto>;
};

export type UserDetailResponse = {
    userId: string;
    email: string;
    roleId: number;
    status: UserStatus;
    createdAt: string;
    fullName: string | null;
    phoneNumber: string | null;
    avatarUrl: string | null;
    headline: string | null;
    profileUpdatedAt: string | null;
    profileVisibility: 'PRIVATE' | 'VISIBLE_TO_EMPLOYERS';
    jobSearchStatus: 'OPEN_TO_WORK' | 'NOT_LOOKING';
    desiredJobTitle: string | null;
    preferredLocation: string | null;
};

export type BanUserResponse = {
    userId: string;
    status: 'BANNED';
    bannedAt: string;
    message: string;
};

export type UnbanUserResponse = {
    userId: string;
    status: 'ACTIVE';
    unbannedAt: string;
    message: string;
};

export type JobStatus = 'PENDING_APPROVAL' | 'ACTIVE' | 'REJECTED' | 'CLOSED' | 'EXPIRED' | 'DELETED';

export type ModerationJobListItemDto = {
    jobId: string;
    title: string;
    companyId: string;
    companyName: string;
    status: JobStatus;
    deadline: string;
    createdAt: string;
};

export type ModerationJobListResponse = {
    items: Array<ModerationJobListItemDto>;
};

export type EmploymentType = 'ON_SITE' | 'REMOTE' | 'HYBRID';

export type ModerationJobDetailResponse = {
    jobId: string;
    title: string;
    description: string;
    requirement: string;
    employmentType: EmploymentType;
    location: string;
    status: JobStatus;
    deadline: string;
    createdAt: string;
    updatedAt: string;
    approvedAt?: string;
    deletedAt?: string;
    deletionReason?: string;
    rejectedAt?: string;
    rejectionReason?: string;
    companyId: string;
    companyName: string;
};

export type ApproveJobResponse = {
    jobId: string;
    status: 'ACTIVE';
    approvedAt: string;
    message: string;
};

export type RejectJobResponse = {
    jobId: string;
    status: 'REJECTED';
    rejectionReason: string;
    rejectedAt: string;
    message: string;
};

export type RejectJobRequest = {
    rejectionReason: string;
};

export type DeleteJobResponse = {
    jobId: string;
    status: 'DELETED';
    deletedAt: string;
    deletionReason: string;
    message: string;
};

export type DeleteJobRequest = {
    deletionReason: string;
};

export type LogAction = 'USER_REGISTERED' | 'USER_LOGGED_IN' | 'USER_LOGGED_OUT' | 'USER_LOGIN_FAILED' | 'USER_BANNED' | 'USER_UNBANNED' | 'PASSWORD_RESET_REQUESTED' | 'PASSWORD_RESET_COMPLETED' | 'PASSWORD_CHANGED' | 'COMPANY_CREATED' | 'COMPANY_UPDATED' | 'JOB_CREATED' | 'JOB_UPDATED' | 'JOB_APPROVED' | 'JOB_REJECTED' | 'JOB_REOPENED' | 'JOB_CLOSED' | 'JOB_DELETED' | 'JOB_EXPIRED' | 'APPLICATION_SUBMITTED' | 'APPLICATION_UNDER_REVIEW' | 'APPLICATION_STATUS_UPDATED' | 'APPLICATION_WITHDRAWN' | 'RESUME_UPLOADED' | 'RESUME_DELETED' | 'PROFILE_UPDATED' | 'AVATAR_CHANGED' | 'JOB_PREFERENCE_UPDATED' | 'SYSTEM_ERROR';

export type LogTargetType = 'USER' | 'JOB' | 'APPLICATION' | 'RESUME' | 'COMPANY' | 'AUTH' | 'SYSTEM';

export type LogLevel = 'INFO' | 'WARN' | 'ERROR';

export type AuditLogListItemDto = {
    logId: string;
    actorId?: string;
    action: LogAction;
    targetId?: string;
    targetType: LogTargetType;
    level: LogLevel;
    message: string;
    createdAt: string;
};

export type AuditLogListResponse = {
    items: Array<AuditLogListItemDto>;
};

export type ResumeDto = {
    id: string;
    title: string;
    fileUrl: string;
    fileType: 'PDF' | 'DOC' | 'DOCX';
    fileSize: number;
    uploadedAt: string;
};

export type GetMyResumeResponse = {
    resumes: Array<ResumeDto>;
};

export type UploadResumeResponse = {
    message: string;
    resume: ResumeDto;
};

export type CompanyProfileDto = {
    id: string;
    name: string;
    city: string;
    district?: string | null;
    description: string;
};

export type CompanyJobListItemDto = {
    id: string;
    title: string;
    employmentType: EmploymentType;
    location: string;
};

export type CompanyProfileResponse = {
    company: CompanyProfileDto;
    jobs: Array<CompanyJobListItemDto>;
};

export type PersonalInformationDto = {
    fullName: string | null;
    dateOfBirth: string | null;
    headline: string | null;
    phoneNumber: string | null;
    city: string | null;
    summary: string | null;
    updatedAt: string;
};

export type UpdatePersonalInformationResponse = {
    message: string;
    userProfile: PersonalInformationDto;
};

export type UpdatePersonalInformationRequest = {
    fullName?: string;
    dateOfBirth?: string | null;
    headline?: string;
    phoneNumber?: string;
    city?: string;
    summary?: string;
};

export type ProfileVisibility = 'PRIVATE' | 'VISIBLE_TO_EMPLOYERS';

export type JobSearchStatus = 'OPEN_TO_WORK' | 'NOT_LOOKING';

export type JobPreferencesDto = {
    profileVisibility: 'VISIBLE_TO_EMPLOYERS' | 'PRIVATE';
    jobSearchStatus: 'OPEN_TO_WORK' | 'NOT_LOOKING';
    desiredJobTitle: string | null;
    preferredLocation: string | null;
    updatedAt: string;
};

export type UpdateJobPreferencesResponse = {
    message: string;
    userJobPreference: JobPreferencesDto;
};

export type UpdateJobPreferencesRequest = {
    profileVisibility?: 'VISIBLE_TO_EMPLOYERS' | 'PRIVATE';
    jobSearchStatus?: 'OPEN_TO_WORK' | 'NOT_LOOKING';
    desiredJobTitle?: string;
    preferredLocation?: string;
};

export type ChangeAvatarResponse = {
    message: string;
    avatarUrl: string;
};

export type ChangePasswordResponse = {
    message: string;
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type JobListItemDto = {
    id: string;
    title: string;
    employmentType: EmploymentType;
    location: string;
    company: {
        name: string;
        id: string;
    };
};

export type SearchJobsResponse = {
    items: Array<JobListItemDto>;
};

export type SearchJobsQuery = {
    keyword?: string;
    location?: string;
};

export type GetJobDetailResponse = {
    id: string;
    title: string;
    description: string;
    requirement: string;
    location: string;
    employmentType: EmploymentType;
    deadline: string;
    company: {
        name: string;
        id: string;
    };
};

export type ApplyJobResponse = {
    applicationId: string;
    status: string;
    appliedAt: string;
};

export type ApplyJobRequest = {
    jobId: string;
    resumeId: string;
};

export type ApplicationStatus = 'SUBMITTED' | 'UNDER_REVIEW' | 'ACCEPTED' | 'REJECTED' | 'WITHDRAWN';

export type ApplicationListDto = {
    applicationId: string;
    jobId: string;
    jobTitle: string;
    companyId: string;
    companyName: string;
    status: ApplicationStatus;
    appliedAt: string;
};

export type WithdrawApplicationResponse = {
    status: ApplicationStatus;
    withdrawnAt: string;
    message: string;
};

export type MyJobListItemDto = {
    jobId: string;
    title: string;
    employmentType: EmploymentType;
    location: string;
    status: JobStatus;
    deadline: string;
    createdAt: string;
    closedAt?: string;
    deletedAt?: string;
};

export type GetMyJobsResponse = {
    items: Array<MyJobListItemDto>;
};

export type GetMyJobDetailResponse = {
    jobId: string;
    title: string;
    description: string;
    requirement: string;
    employmentType: EmploymentType;
    location: string;
    status: JobStatus;
    deadline: string;
    createdAt: string;
    updatedAt: string;
    closedAt?: string;
    deletedAt?: string;
    approvedAt?: string;
    rejectedAt?: string;
    rejectionReason?: string;
};

export type CreateJobPostingResponse = {
    jobId: string;
    title: string;
    description: string;
    requirement: string;
    employmentType: EmploymentType;
    location: string;
    deadline: string;
    status: 'PENDING_APPROVAL';
    createdAt: string;
};

export type JobPostingBody = {
    title: string;
    description: string;
    requirement: string;
    employmentType: EmploymentType;
    location: string;
    deadline: string;
};

export type CreateJobPostingRequest = JobPostingBody;

export type UpdateJobPostingResponse = {
    jobId: string;
    title: string;
    description: string;
    requirement: string;
    employmentType: EmploymentType;
    location: string;
    deadline: string;
    status: 'PENDING_APPROVAL';
    updatedAt: string;
};

export type UpdateJobPostingRequest = JobPostingBody;

export type CloseJobPostingResponse = {
    jobId: string;
    status: 'CLOSED';
    closedAt: string;
    message: string;
};

export type ReopenJobPostingResponse = {
    jobId: string;
    status: 'PENDING_APPROVAL';
    message: string;
};

export type DeleteJobPostingResponse = {
    jobId: string;
    status: 'DELETED';
    deletedAt: string;
    message: string;
};

export type CompanyResponse = {
    companyId: string;
    name: string;
    city: string;
    district?: string;
    description: string;
    createdAt: string;
};

export type CreateCompanyRequest = {
    name: string;
    district?: string;
    city: string;
    description: string;
};

export type UpdateCompanyRequest = {
    name: string;
    district?: string;
    city: string;
    description: string;
};

export type EmployerApplicationListItemDto = {
    applicationId: string;
    candidateName?: string;
    candidateEmail: string;
    resumeId: string;
    resumeTitle: string;
    applicationStatus: ApplicationStatus;
    appliedAt: string;
};

export type EmployerApplicationListResponse = {
    items: Array<EmployerApplicationListItemDto>;
};

export type EmployerApplicationResponse = {
    applicationId: string;
    candidateName?: string;
    candidateEmail: string;
    candidateHeadline?: string;
    candidatePhoneNumber?: string;
    candidateCity?: string;
    resumeId: string;
    resumeTitle: string;
    resumeFileUrl: string;
    jobId: string;
    jobTitle: string;
    applicationStatus: ApplicationStatus;
    appliedAt: string;
    underReviewAt?: string;
    withdrawnAt?: string;
    decidedAt?: string;
    rejectionReason?: string;
    updatedAt: string;
};

export type PutApplicationUnderReviewResponse = {
    applicationId: string;
    applicationStatus: 'UNDER_REVIEW';
    underReviewAt: string;
    message: string;
};

export type UpdateApplicationStatusResponse = {
    applicationId: string;
    applicationStatus: 'ACCEPTED' | 'REJECTED';
    decidedAt?: string;
    rejectionReason?: string;
    message: string;
};

export type UpdateApplicationStatusRequest = {
    decision: 'ACCEPTED' | 'REJECTED';
    rejectionReason?: string;
};

export type LoginResponse = {
    accessToken: string;
    user: {
        status: string;
        roleId: number;
        email: string;
        id: string;
    };
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type RegisterResponse = {
    user: {
        status: 'ACTIVE' | 'BANNED';
        roleId: number;
        email: string;
        id: string;
    };
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type LogoutResponse = {
    message: string;
};

export type ForgotPasswordResponse = {
    message: string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ResetPasswordResponse = {
    message: string;
};

export type ResetPasswordRequest = {
    token: string;
    newPassword: string;
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        email?: string;
    };
    url: '/admin/users';
};

export type GetUsersResponses = {
    /**
     * OK
     */
    200: UserListResponse;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetUserDetailData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/admin/users/{userId}';
};

export type GetUserDetailResponses = {
    /**
     * OK
     */
    200: UserDetailResponse;
};

export type GetUserDetailResponse = GetUserDetailResponses[keyof GetUserDetailResponses];

export type BanUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/admin/users/{userId}/ban';
};

export type BanUserResponses = {
    /**
     * OK
     */
    200: BanUserResponse;
};

export type BanUserResponse2 = BanUserResponses[keyof BanUserResponses];

export type UnbanUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/admin/users/{userId}/unban';
};

export type UnbanUserResponses = {
    /**
     * OK
     */
    200: UnbanUserResponse;
};

export type UnbanUserResponse2 = UnbanUserResponses[keyof UnbanUserResponses];

export type GetModerationJobsData = {
    body?: never;
    path?: never;
    query?: {
        status?: JobStatus;
    };
    url: '/admin/jobs';
};

export type GetModerationJobsResponses = {
    /**
     * OK
     */
    200: ModerationJobListResponse;
};

export type GetModerationJobsResponse = GetModerationJobsResponses[keyof GetModerationJobsResponses];

export type GetModerationJobDetailData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/admin/jobs/{jobId}';
};

export type GetModerationJobDetailResponses = {
    /**
     * OK
     */
    200: ModerationJobDetailResponse;
};

export type GetModerationJobDetailResponse = GetModerationJobDetailResponses[keyof GetModerationJobDetailResponses];

export type ApproveJobPostingData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/admin/jobs/{jobId}/approve';
};

export type ApproveJobPostingResponses = {
    /**
     * OK
     */
    200: ApproveJobResponse;
};

export type ApproveJobPostingResponse = ApproveJobPostingResponses[keyof ApproveJobPostingResponses];

export type RejectJobPostingData = {
    body: RejectJobRequest;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/admin/jobs/{jobId}/reject';
};

export type RejectJobPostingResponses = {
    /**
     * OK
     */
    200: RejectJobResponse;
};

export type RejectJobPostingResponse = RejectJobPostingResponses[keyof RejectJobPostingResponses];

export type RemoveJobPostingData = {
    body: DeleteJobRequest;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/admin/jobs/{jobId}/delete';
};

export type RemoveJobPostingResponses = {
    /**
     * OK
     */
    200: DeleteJobResponse;
};

export type RemoveJobPostingResponse = RemoveJobPostingResponses[keyof RemoveJobPostingResponses];

export type GetAuditLogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/logs';
};

export type GetAuditLogsResponses = {
    /**
     * OK
     */
    200: AuditLogListResponse;
};

export type GetAuditLogsResponse = GetAuditLogsResponses[keyof GetAuditLogsResponses];

export type GetMyResumesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/resumes';
};

export type GetMyResumesResponses = {
    /**
     * OK
     */
    200: GetMyResumeResponse;
};

export type GetMyResumesResponse = GetMyResumesResponses[keyof GetMyResumesResponses];

export type UploadResumeData = {
    body: {
        resumeTitle: string;
        resumeFile: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/users/me/resumes';
};

export type UploadResumeResponses = {
    /**
     * Created
     */
    201: UploadResumeResponse;
};

export type UploadResumeResponse2 = UploadResumeResponses[keyof UploadResumeResponses];

export type DeleteResumeData = {
    body?: never;
    path: {
        resumeId: string;
    };
    query?: never;
    url: '/users/me/resumes/{resumeId}';
};

export type DeleteResumeResponses = {
    /**
     * OK
     */
    200: {
        message: string;
    };
};

export type DeleteResumeResponse = DeleteResumeResponses[keyof DeleteResumeResponses];

export type GetCompanyProfileData = {
    body?: never;
    path: {
        companyId: string;
    };
    query?: never;
    url: '/companies/{companyId}';
};

export type GetCompanyProfileResponses = {
    /**
     * OK
     */
    200: CompanyProfileResponse;
};

export type GetCompanyProfileResponse = GetCompanyProfileResponses[keyof GetCompanyProfileResponses];

export type GetMyProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/profile';
};

export type GetMyProfileResponses = {
    /**
     * OK
     */
    200: {
        profile: {
            updatedAt: string;
            avatarUrl: string;
            city: string;
            phoneNumber: string;
            summary: string;
            headline: string;
            dateOfBirth: string;
            fullName: string;
        };
    };
};

export type GetMyProfileResponse = GetMyProfileResponses[keyof GetMyProfileResponses];

export type UpdatePersonalInformationData = {
    body: UpdatePersonalInformationRequest;
    path?: never;
    query?: never;
    url: '/users/me/profile';
};

export type UpdatePersonalInformationResponses = {
    /**
     * OK
     */
    200: UpdatePersonalInformationResponse;
};

export type UpdatePersonalInformationResponse2 = UpdatePersonalInformationResponses[keyof UpdatePersonalInformationResponses];

export type GetJobPreferenceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/job-preference';
};

export type GetJobPreferenceResponses = {
    /**
     * OK
     */
    200: {
        preference: {
            preferredLocation: string;
            desiredJobTitle: string;
            jobSearchStatus: JobSearchStatus;
            profileVisibility: ProfileVisibility;
        };
    };
};

export type GetJobPreferenceResponse = GetJobPreferenceResponses[keyof GetJobPreferenceResponses];

export type UpdateJobPreferenceData = {
    body: UpdateJobPreferencesRequest;
    path?: never;
    query?: never;
    url: '/users/me/job-preference';
};

export type UpdateJobPreferenceResponses = {
    /**
     * OK
     */
    200: UpdateJobPreferencesResponse;
};

export type UpdateJobPreferenceResponse = UpdateJobPreferenceResponses[keyof UpdateJobPreferenceResponses];

export type ChangeAvatarData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/users/me/avatar';
};

export type ChangeAvatarResponses = {
    /**
     * OK
     */
    200: ChangeAvatarResponse;
};

export type ChangeAvatarResponse2 = ChangeAvatarResponses[keyof ChangeAvatarResponses];

export type ChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/users/me/change-password';
};

export type ChangePasswordResponses = {
    /**
     * OK
     */
    200: ChangePasswordResponse;
};

export type ChangePasswordResponse2 = ChangePasswordResponses[keyof ChangePasswordResponses];

export type SearchJobsData = {
    body?: never;
    path?: never;
    query?: {
        keyword?: string;
        location?: string;
    };
    url: '/jobs';
};

export type SearchJobsResponses = {
    /**
     * OK
     */
    200: SearchJobsResponse;
};

export type SearchJobsResponse2 = SearchJobsResponses[keyof SearchJobsResponses];

export type GetJobDetailData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/jobs/{jobId}';
};

export type GetJobDetailResponses = {
    /**
     * OK
     */
    200: GetJobDetailResponse;
};

export type GetJobDetailResponse2 = GetJobDetailResponses[keyof GetJobDetailResponses];

export type ApplyJobsData = {
    body: ApplyJobRequest;
    path?: never;
    query?: never;
    url: '/applications';
};

export type ApplyJobsResponses = {
    /**
     * Created
     */
    201: ApplyJobResponse;
};

export type ApplyJobsResponse = ApplyJobsResponses[keyof ApplyJobsResponses];

export type GetMyApplicationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/applications/my';
};

export type GetMyApplicationsResponses = {
    /**
     * OK
     */
    200: Array<ApplicationListDto>;
};

export type GetMyApplicationsResponse = GetMyApplicationsResponses[keyof GetMyApplicationsResponses];

export type WithdrawApplicationData = {
    body?: never;
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/applications/{applicationId}/withdraw';
};

export type WithdrawApplicationResponses = {
    /**
     * OK
     */
    200: WithdrawApplicationResponse;
};

export type WithdrawApplicationResponse2 = WithdrawApplicationResponses[keyof WithdrawApplicationResponses];

export type GetMyJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/employer/jobs';
};

export type GetMyJobsResponses = {
    /**
     * OK
     */
    200: GetMyJobsResponse;
};

export type GetMyJobsResponse2 = GetMyJobsResponses[keyof GetMyJobsResponses];

export type CreateJobPostingData = {
    body: JobPostingBody;
    path?: never;
    query?: never;
    url: '/employer/jobs';
};

export type CreateJobPostingResponses = {
    /**
     * Created
     */
    201: CreateJobPostingResponse;
};

export type CreateJobPostingResponse2 = CreateJobPostingResponses[keyof CreateJobPostingResponses];

export type GetMyJobDetailData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/employer/jobs/{jobId}';
};

export type GetMyJobDetailResponses = {
    /**
     * OK
     */
    200: GetMyJobDetailResponse;
};

export type GetMyJobDetailResponse2 = GetMyJobDetailResponses[keyof GetMyJobDetailResponses];

export type UpdateJobPostingData = {
    body: JobPostingBody;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/employer/jobs/{jobId}';
};

export type UpdateJobPostingResponses = {
    /**
     * OK
     */
    200: UpdateJobPostingResponse;
};

export type UpdateJobPostingResponse2 = UpdateJobPostingResponses[keyof UpdateJobPostingResponses];

export type CloseJobPostingData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/employer/jobs/{jobId}/close';
};

export type CloseJobPostingResponses = {
    /**
     * OK
     */
    200: CloseJobPostingResponse;
};

export type CloseJobPostingResponse2 = CloseJobPostingResponses[keyof CloseJobPostingResponses];

export type ReopenJobPostingData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/employer/jobs/{jobId}/reopen';
};

export type ReopenJobPostingResponses = {
    /**
     * OK
     */
    200: ReopenJobPostingResponse;
};

export type ReopenJobPostingResponse2 = ReopenJobPostingResponses[keyof ReopenJobPostingResponses];

export type DeleteJobPostingData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/employer/jobs/{jobId}/delete';
};

export type DeleteJobPostingResponses = {
    /**
     * OK
     */
    200: DeleteJobPostingResponse;
};

export type DeleteJobPostingResponse2 = DeleteJobPostingResponses[keyof DeleteJobPostingResponses];

export type GetCompanyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/employer/company';
};

export type GetCompanyResponses = {
    /**
     * OK
     */
    200: CompanyResponse;
};

export type GetCompanyResponse = GetCompanyResponses[keyof GetCompanyResponses];

export type UpdateCompanyData = {
    body: UpdateCompanyRequest;
    path?: never;
    query?: never;
    url: '/employer/company';
};

export type UpdateCompanyResponses = {
    /**
     * OK
     */
    200: CompanyResponse;
};

export type UpdateCompanyResponse = UpdateCompanyResponses[keyof UpdateCompanyResponses];

export type CreateCompanyData = {
    body: CreateCompanyRequest;
    path?: never;
    query?: never;
    url: '/employer/company';
};

export type CreateCompanyResponses = {
    /**
     * Created
     */
    201: CompanyResponse;
};

export type CreateCompanyResponse = CreateCompanyResponses[keyof CreateCompanyResponses];

export type GetJobApplicationsData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/employer/jobs/{jobId}/applications';
};

export type GetJobApplicationsResponses = {
    /**
     * OK
     */
    200: EmployerApplicationListResponse;
};

export type GetJobApplicationsResponse = GetJobApplicationsResponses[keyof GetJobApplicationsResponses];

export type GetJobApplicationDetailData = {
    body?: never;
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/employer/applications/{applicationId}';
};

export type GetJobApplicationDetailResponses = {
    /**
     * OK
     */
    200: EmployerApplicationResponse;
};

export type GetJobApplicationDetailResponse = GetJobApplicationDetailResponses[keyof GetJobApplicationDetailResponses];

export type PutApplicationUnderReviewData = {
    body?: never;
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/employer/applications/{applicationId}/under-review';
};

export type PutApplicationUnderReviewResponses = {
    /**
     * OK
     */
    200: PutApplicationUnderReviewResponse;
};

export type PutApplicationUnderReviewResponse2 = PutApplicationUnderReviewResponses[keyof PutApplicationUnderReviewResponses];

export type UpdateApplicationStatusData = {
    body: UpdateApplicationStatusRequest;
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/employer/applications/{applicationId}/status';
};

export type UpdateApplicationStatusResponses = {
    /**
     * OK
     */
    200: UpdateApplicationStatusResponse;
};

export type UpdateApplicationStatusResponse2 = UpdateApplicationStatusResponses[keyof UpdateApplicationStatusResponses];

export type AuthenticateUserData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthenticateUserResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type AuthenticateUserResponse = AuthenticateUserResponses[keyof AuthenticateUserResponses];

export type RegisterUserData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterUserResponses = {
    /**
     * Created
     */
    201: RegisterResponse;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type LogoutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutUserResponses = {
    /**
     * OK
     */
    200: LogoutResponse;
};

export type LogoutUserResponse = LogoutUserResponses[keyof LogoutUserResponses];

export type RequestPasswordResetData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type RequestPasswordResetResponses = {
    /**
     * OK
     */
    200: ForgotPasswordResponse;
};

export type RequestPasswordResetResponse = RequestPasswordResetResponses[keyof RequestPasswordResetResponses];

export type ResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetPasswordResponses = {
    /**
     * OK
     */
    200: ResetPasswordResponse;
};

export type ResetPasswordResponse2 = ResetPasswordResponses[keyof ResetPasswordResponses];

export type ValidateResetTokenData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/auth/reset-password/validate';
};

export type ValidateResetTokenResponses = {
    /**
     * OK
     */
    200: {
        valid: boolean;
    };
};

export type ValidateResetTokenResponse = ValidateResetTokenResponses[keyof ValidateResetTokenResponses];
